### ISSUE TITLE
Add "Chore" tickbox in "Type of change"

### ISSUE THREAD

**Issue by KaarlisCaune** [Qminder/.github#9] opened 2023-06-20 11:37 UTC
It's given as an example to add in the title, but doesn't exist in the list. Usually I've been keeping the list empty in chore-type PRs, which is not how it should work ideally

Maybe something like 

- [ ] _Chore (work that doesn't change functionality or fix anything, but is needed anyway)_ <-- I'm not sure how to define it really.

**Comment by boxmein** [comment] 2023-06-20 12:31
I had a quick verbal discussion with Siim on this section overall, and it seems to actually be a duplicate of the conventional-commits prefix.

If we already do `fix:` or `chore:` or `feat: BREAKING:` then there's no real need to have the type-of-change section.

**Closed as completed** 2023-06-27 13:25 UTC
